### PR TITLE
fix: popup insertion logic

### LINKED ISSUE #92: Misplaced inline popups
The popup placement logic inserts the popup markup after a closing `p` tag. This can lead to unfortunate placement of the popup, such as here, where the popup markup was placed inside of a `blockquote`:

image

The placement logic should only be concerned with `p` elements which are direct descendants of `.entry-content`.

### PR DESCRIPTION
**Pull request by adekbadek**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

By matching block end comments instead of paragraph end tags, the popup will always be inserted between blocks, and not inside of a block (which might have paragraphs inside).

Resolves #92

### How to test the changes in this Pull Request:

1. On `master`
1. Add a quote block to a post
2. Add an inline popup and try to set the "Approximate position" so that the popup placed is where the quote is
2. Observe in preview that the inline popup in inserted into the quote block
3. Switch to this branch
4. Observe in preview that the inline popup and quote block are not conjoined

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by adekbadek** [comment]
@claudiulodro I've followed you suggestion: 77911ff720ba318b333fbb037b55827950135deb

File: includes/class-newspack-popups-inserter.php [hunk 1]
```diff
@@ -180,27 +180,25 @@ public static function insert_popup( $content = '', $popup = [] ) {
...
+		$output      = '';
+		$is_inserted = false;
+		foreach ( $blocks as $block ) {
+			$block_content = render_block( $block );
+			$pos          += strlen( $block_content );
+			if ( ! $is_inserted && $pos >= $precise_position ) {
+				$output     .= '<!-- wp:shortcode -->' . $popup_markup . '<!-- /wp:shortcode -->';
+				$is_inserted = true;
 			}
+			$output .= $block_content;
```
Comment (claudiulodro) [inline includes/class-newspack-popups-inserter.php:198]: A site with this plugin active will have its blocks rendered at priority 1 in `the_content`. I'm not sure whether this will cause issues from other plugins that assume things, but I think there is definitely the potential for some weirdness. For example, a plugin that does something with raw block content and hooks into `the_content` at priority 4 will not have the raw block content it expects. The unknown unknowns here are my main concern. 

An approach that only inserts the shortcode block at the appropriate place and doesn't otherwise modify the content would solve this issue, e.g.
```
		$blocks      = parse_blocks( $content );
		$pos         = 0;
		$output      = '';
		$is_inserted = false;
		foreach ( $blocks as $block ) {
             $original_block_markup = '?????'; // Need to figure this out somehow I think.
			$block_content = render_block( $block );
			$pos          += strlen( $block_content );
			if ( ! $is_inserted && $pos >= $precise_position ) {
				$output     .= '<!-- wp:shortcode -->' . $popup_markup . '<!-- /wp:shortcode -->';
				$is_inserted = true;
			}
			$output .= $original_block_markup; // Let the block parser handle the block rendering at `the_content` priority ~9. 
```

It's a difficult problem to figure out the original block markup from the parsed block, though. I'm not sure how that would work.

Comment (adekbadek) [reply includes/class-newspack-popups-inserter.php:198]: I'm not that familiar with the potential implications of priority here. Could you please share some code that a plugin might introduce and that would break things?

Comment (claudiulodro) [reply includes/class-newspack-popups-inserter.php:198]: > Could you please share some code that a plugin might introduce and that would break things?

For example, if there were two plugins injecting popups into the content in the exact same way as this PR (Newspack Popups A and Newspack Popups B), only the first plugin would correctly insert the popup. Newspack Popups B wouldn't work correctly.

Here's a contrived example that demonstrates it further:
```
// Remove all image blocks from the content.
add_filter( 'the_content', function( $content ) {
	$regex = '#<!-- wp:image.*\/wp:image -->#sU';
	return preg_replace( $regex, '', $content );
}, 2 );
```

Without this PR, this will correctly remove all image blocks from the content. With this PR active, this will do nothing.

I fear I may be overly concerned with a "correct" logic for this, though. I've been thinking about this further. I think we'll likely be OK. Let's go ahead and release this version and see if anything surfaces. It seems pretty unlikely another plugin would do something similar.

Comment (claudiulodro) [reply includes/class-newspack-popups-inserter.php:198]: Leaving a note here about a better solution I've thought of because I think this did cause issues after all, in the edge case where 2+ inline campaigns are used.

We can combine the different approaches by injecting popups into the **fully rendered** content (run the filter at priority `99` instead of `1`) and **only counting top-level paragraph elements**. The tricky part is how to accurately count top-level paragraphs (it's not feasible with regex). [DOMDocument](https://www.php.net/manual/en/class.domdocument.php) is probably the most straightforward solution I think.
