### PR TITLE
fix: category/tag exclusion fields in block editor

### LINKED ISSUE #932: Can't exclude prompts by more than one category
In the Advanced Settings panel of a prompt, there are fields for excluding categories and tags. 

However, the category field won't take multiple entries. Publisher would like to exclude from multiple categories. 

https://user-images.githubusercontent.com/48489469/182924174-8cb0ca7f-8dbd-4c8a-8da6-6d4c1f7c96bb.mov

### PR DESCRIPTION
**Pull request by dkoo**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes the category/term exclusion fields in the single prompt editor so that multiple terms can be selected for a prompt.

Closes #932.

### How to test the changes in this Pull Request:

1. On `master`, create a prompt with a category and tag in the exclusion fields ("Advanced Settings" sidebar).
2. Check out this branch. Confirm that the previously selected category/tag are still shown for the prompt, and that #932 can't be replicated.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

File: src/editor/AdvancedSidebar.js [hunk 1]
```diff
@@ -8,74 +8,34 @@
...
-					key="categories"
-					tokens={ excluded_categories }
-					onChange={ _excluded_categories => {
-						onMetaFieldChange( { excluded_categories: _excluded_categories } );
-					} }
-					fetchSuggestions={ search => fetchTaxonomySuggestions( '/wp/v2/categories', search ) }
-					fetchSavedInfo={ taxonomyIDs => fetchSavedTaxonomies( '/wp/v2/categories', taxonomyIDs ) }
-					label={ __( 'Excluded Categories', 'newspack-blocks' ) }
+				<CategoryAutocomplete
+					label={ __( 'Post categories', 'newspack ' ) }
```
Comment (adekbadek) [inline src/editor/AdvancedSidebar.js:22]: :)

```suggestion
					label={ __( 'Excluded post categories', 'newspack-popups ' ) }
```

File: src/editor/AdvancedSidebar.js [hunk 2]
```diff
@@ -8,74 +8,34 @@
...
-					key="tags"
-					tokens={ excluded_tags }
-					onChange={ _excluded_tags => {
-						onMetaFieldChange( { excluded_tags: _excluded_tags } );
-					} }
-					fetchSuggestions={ search => fetchTaxonomySuggestions( '/wp/v2/tags', search ) }
-					fetchSavedInfo={ taxonomyIDs => fetchSavedTaxonomies( '/wp/v2/tags', taxonomyIDs ) }
-					label={ __( 'Excluded Tags', 'newspack-blocks' ) }
+				<CategoryAutocomplete
+					label={ __( 'Post tags', 'newspack ' ) }
```
Comment (adekbadek) [inline src/editor/AdvancedSidebar.js:31]:
```suggestion
					label={ __( 'Excluded post tags', 'newspack-popups ' ) }
```

**Review by adekbadek — APPROVED** [review]
Pre-approving, since only some wording changes are needed.

**Comment by dkoo** [comment]
At this point I'll wait until the next release goes out imminently before merging this, to avoid potential conflicts.

**Comment by dkoo** [comment]
Rebasing to `master` so we can re-release after the last release job failed.
