### PR TITLE
fix: introduce blacklisted blocks to ignore when inserting prompts

### LINKED ISSUE #465: Incorrect prompt insertion when post content contains jetpack/slideshow blocks
First reported by @joeboydston.

This is a hard one to replicate, but sometimes inline prompts will be inserted into the wrong areas of an article if the content contains a `jetpack/slideshow` block.

Example page where it's happening: http://mississippitoday.org/2021/02/26/food-thats-going-to-stick-to-your-ribs-the-significance-of-soul-food-in-yalobusha-county/

In a new session, three inline prompts are supposed to be injected at 25%, 50%, and 100% of the content, but where they're really being injected is all together toward the top of the article, like so:

Screen Shot 2021-03-03 at 3 23 27 PM

This is because the `$block_content` calculated [here](https://github.com/Automattic/newspack-popups/blob/master/includes/class-newspack-popups-inserter.php#L250) is sometimes much longer for Jetpack Slideshow blocks than expected—in the case of this page, it's almost as long as the total `$content` length, somehow. I can't determine why, but this causes the prompt insertion logic to think that the article is much longer than it really is, and then the prompts get inserted at the wrong locations.

**Expected:** The prompts should get inserted at roughly 25%, 50%, and 100% of the article content, with or without the slideshow block.

### PR DESCRIPTION
**Pull request by dkoo**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

#466 and #468 tweaked the inline prompt insertion logic to account for slideshows, but it wasn't enough to truly fix the insertion logic in posts with slideshows. This PR introduces the concept of ignoring certain types of blocks for purposes of inline prompt insertion; these blocks may contain a massive amount of block content but will only take up a small amount of visual space in the post content, so their content length shouldn't be used for purposes of inline prompt insertion.

The new feature lets us designate any block to be ignored by adding it to the `$blacklisted_blocks` array in `class-newspack-popups-inserter.php`. At time of PR, only `jetpack/slideshow` and `newspack-blocks/carousel` are designated as such, but more can be added if they're found to cause similar issues with inline prompt insertion.

Closes #465 (again).

### How to test the changes in this Pull Request:

1. Create a post with 10 very short paragraphs, perhaps a sentence or two each.
2. At the top of the post, insert a Jetpack slideshow block with a truly massive number of slides (at least 20, preferably with captions, the more the better to inflate the size of its `innerHTML`).
3. Create and publish several inline prompts at various insertion points try (0%, 25%, 50%, 75%, and 100%).
4. On `master`, view the post while not logged in and observe that several of the inline prompts appear bunched together toward the top of the post.
5. Check out this branch and refresh the post. Now confirm that the prompts appear more evenly spaced throughout the short paragraphs.
6. Edit the post and replace the slideshow with a Newspack posts carousel block. Make sure the block is set to a large number of posts (20+).
7. Repeat steps 4-5 and confirm the same issue on `master`, and a similar result on this branch.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by adekbadek — COMMENTED** [review]
This causes the blacklisted blocks to be simply disregarded - this way if a post starts with one of these, and there's an inline prompt at 0%, it will be placed after the blacklisted block. 
Perhaps instead of ignoring the blacklisted blocks in computation, they can be given a fake length? This way a prompt at 0% would render always before any content.

**Comment by dkoo** [comment]
> This causes the blacklisted blocks to be simply disregarded - this way if a post starts with one of these, and there's an inline prompt at 0%, it will be placed after the blacklisted block. Perhaps instead of ignoring the blacklisted blocks in computation, they can be given a fake length? This way a prompt at 0% would render always before any content.

This is true (and I like your term "blacklisted" better than override...was having trouble thinking of the word I wanted yesterday!). 2f66203 gives blacklisted blocks a length of `1` so that prompts at 0% will still appear before them, even when they're at the top of the post. The very small length means that they still have little to no effect on insertion logic after that.

To test:

1. Ensure that the first block in the post is a blacklisted block (slideshow or carousel) with lots of slides
2. Confirm that an inline prompt with 0% placement appears before the block
3. Also confirm that a prompt at 100% will appear after the post content, even if the last block is a blacklisted block.

File: includes/class-newspack-popups-inserter.php [hunk 1]
```diff
@@ -221,12 +221,21 @@ function ( $popup ) use ( $shortcoded_popups_ids ) {
...
 
-		// Dynamic blocks might render an arbitrary amount of content, so the length of the content string is
-		// not an accurate representation of the content length.
-		$total_length = 0;
-		foreach ( parse_blocks( $content ) as $block ) {
-			$block_content = $block['innerHTML'];
-			$total_length += strlen( wp_strip_all_tags( $block_content ) );
+		// For certain types of blocks, their innerHTML is not a good representation of the length of their content.
+		// For example, slideshows may have an arbitrary amount of slide content, but only show one slide at a time.
+		// Don't insert prompts adjacent to these.
```
Comment (adekbadek) [inline includes/class-newspack-popups-inserter.php:226]: Nit: this line in the comment is not accurate after the recent changes ;)

**Review by adekbadek — APPROVED** [review]

File: includes/class-newspack-popups-inserter.php (hunk 1 above)
Comment (dkoo) [reply includes/class-newspack-popups-inserter.php]: Updated in f479c4d 😄
